# Generated by Django 6.1.1 on 2026-09-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_assigned_to_task_task_project_status_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='task_project_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_project_due_idx',
        ),
    ]
